# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import service.service_pb2 as service__pb2


class RecognitionStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Recognize = channel.stream_stream(
        '/Service.Recognition/Recognize',
        request_serializer=service__pb2.Request.SerializeToString,
        response_deserializer=service__pb2.Response.FromString,
        )


class RecognitionServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Recognize(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RecognitionServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Recognize': grpc.stream_stream_rpc_method_handler(
          servicer.Recognize,
          request_deserializer=service__pb2.Request.FromString,
          response_serializer=service__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Service.Recognition', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
